# Docker Compose konfigurace pro Redis cache
# Používá moderní verzi compose syntaxe

version: '3.8'

services:
  # Redis služba pro ukládání cache dat
  redis:
    image: redis:latest # Oficiální Redis image z Docker Hub
    container_name: restaurant-redis # Přátelský název kontejneru
    ports:
      - "6379:6379" # Mapování portu 6379 z hostitele do kontejneru
    volumes:
      - redis-data:/data # Persistentní úložiště pro cache data

# Definice volume pro persistentní úložiště
# Zajišťuje, že cache data přežijí restart kontejneru
volumes:
  redis-data:
