# Docker Compose configuration for Redis cache
# Uses modern compose syntax

version: '3.8'

services:
  # Redis service for storing cache data
  redis:
    image: redis:latest # Official Redis image from Docker Hub
    container_name: restaurant-redis # Friendly container name
    ports:
      - "6379:6379" # Map port 6379 from host to container
    volumes:
      - redis-data:/data # Persistent storage for cache data

# Volume definition for persistent storage
# Ensures cache data survives container restart
volumes:
  redis-data:
