# render.yaml - Defines services for Render Blueprint

services:
  # 1. Redis Service
  - type: redis
    name: menu-cache
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow All

  # 2. OCR/PDF Service (Python/FastAPI)
  - type: web
    name: restaurant-ocr
    env: docker
    dockerfilePath: ./ocr-service/Dockerfile
    dockerContext: ./ocr-service
    plan: free

  # 3. Backend Service (NestJS)
  - type: web
    name: restaurant-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Set value manually in Render dashboard
      - key: REDIS_URL
        fromService:
          type: redis
          name: menu-cache
          property: connectionString
      # ---> ADD OCR SERVICE URL <---
      - key: OCR_SERVICE_URL
        value: http://restaurant-ocr:8000 # Internal URL for OCR service

  # 4. Frontend Service (React/Nginx)
  - type: web
    name: restaurant-client
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free
    build:
      dockerBuildArgs:
        REACT_APP_API_URL: http://restaurant-server:3001
