# render.yaml - Defines services for Render Blueprint

services:
  # 1. Redis Service
  - type: redis
    name: menu-cache
    plan: free
    # Add IP Allow List - Allow connections from anywhere (adjust if needed for security)
    # Render's internal services should be able to connect.
    ipAllowList:
      - cidr: 0.0.0.0/0
        description: Allow All # For simplicity, restrict later if needed

  # 2. OCR/PDF Service (Python/FastAPI)
  - type: web
    name: restaurant-ocr
    env: docker
    dockerfilePath: ./ocr-service/Dockerfile
    dockerContext: ./ocr-service
    plan: free
    # healthCheckPath: /health # Optional

  # 3. Backend Service (NestJS)
  - type: web
    name: restaurant-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Set value manually in Render dashboard
      - key: REDIS_URL
        fromService:
          type: redis
          name: menu-cache
          # Correct property name: use connectionString
          property: connectionString # <-- ZMĚNA Z internalUrl

  # 4. Frontend Service (React/Nginx)
  - type: web
    name: restaurant-client
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free
